repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 9136088a246768144165fcc3ecc3d31bb686920a  # frozen: v3.3.0
  hooks:
  - id: check-yaml
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: eae6397e4c259ed3d057511f6dd5330b92867e62  # frozen: v1.6.0
  hooks:
  - id: python-use-type-annotations
  - id: python-check-blanket-noqa
- repo: https://github.com/timothycrosley/isort
  rev: 6bb47b7acc1554ecb59d2855e9110c447162f674  # frozen: 5.6.4
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: e66be67b9b6811913470f70c28b4d50f94d05b22  # frozen: 20.8b1
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: bb6a530e28acab8d3551043b3e8709db8bcbac6b  # frozen: 3.8.4
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
    - flake8-builtins
    - flake8-comprehensions
- repo: https://github.com/myint/docformatter
  rev: de0bf8fa254d25a01383fecdb6335bea01daeae3  # frozen: v1.3.1
  hooks:
  - id: docformatter
- repo: https://github.com/executablebooks/mdformat
  rev: 492440cdb4f3ca87eff24dea09c85881b0e5d597  # frozen: 0.4.0
  hooks:
  - id: mdformat
    files: 'README.md'
    additional_dependencies:
    - mdformat-toc
